spring.application.name=dsdr
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dsdr?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis-plus.config-location=classpath:/mybatis-config.xml

# ?? FreeMarker ??
spring.freemarker.enabled=true
# ??????
spring.freemarker.cache=false
# Content Type
spring.freemarker.content-type=text/html
# ??
spring.freemarker.charset=utf-8
# ????
spring.freemarker.suffix=.ftl
# ?? request ?????
spring.freemarker.request-context-attribute=request
# ???? request ?????
spring.freemarker.expose-request-attributes=false
# ???? session ?????
spring.freemarker.expose-session-attributes=false
# request ??????????? controller ? model ????
spring.freemarker.allow-request-override=true
# session ??????????? controller ? model ????
spring.freemarker.allow-session-override=true
# ????????
spring.freemarker.expose-spring-macro-helpers=true
# ?????????????
spring.freemarker.check-template-location=true
# ???????????
spring.freemarker.prefer-file-system-access=true
# ??????????
spring.freemarker.template-loader-path=classpath:/templates/
# FreeMarker ???
spring.freemarker.settings.datetime_format=yyyy-MM-dd HH:mm:ss
spring.freemarker.settings.template_update_delay=30m
spring.freemarker.settings.default_encoding=utf-8
spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis
spring.session.timeout=600s
spring.mvc.static-path-pattern=/static/**
# ??????
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example=TRACE

# ??????????
logging.file.name=app.log
logging.file.path=/var/logs/myapp

# ????????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n